name: CI
on:
  - push
  - pull_request
  - workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: c-hive/gha-npm-cache@v1
      - run: npm ci
      - run: npm test
